name: test-shared-workflow

on:
  workflow_call:
    inputs:
      work_dir:
        description: Workspace directory
        default: BUILD
        required: true
        type: string
    secrets:
      github_app_id:
        description: GitHub App ID
        required: true

envs:
  GH_REF_NAME: ${{ github.ref_name }}

jobs:
  setup:
    runs-on: ubuntu-latest

    env:
      GH_APP_ID: ${{ secrets.github_app_id }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: source
          persist-credentials: false

      - run: |
          echo "app_id: ${GH_APP_ID}; ref_name: ${GH_REF_NAME}"
