name: test-pr-action

on:
  workflow_dispatch: # for manual testing

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changes
        id: update
        run: |
          date +%s >> test.txt

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: New test release
          body: Automated PR created by github-actions.
          commit-message: wip!
          branch: test-branch
          base: main
          labels: kind/automation
