name: test-backport-action

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - run: gh pr comment $PR_URL --body "All your base are belong to us!"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout grafana-github-actions
        uses: actions/checkout@v4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          # pin the version to before https://github.com/grafana/grafana-github-actions/pull/113 because
          # we don't want to have the same strict rules for PR labels
          ref: d284afd314ca3625c23595e9f62b52d215ead7ce

      - name: Install grafana-github-actions
        run: npm install --production --prefix ./actions

      - name: Run backport
        id: backport
        #if: ${{ ! github.event.pull_request.head.repo.fork }}
        uses: ./actions/backport
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labelsToAdd: "backport"
          title: "[{{base}}] {{originalTitle}}"
