name: test-slack-workflow

on:
  workflow_dispatch: # for manual testing

permissions:
  id-token: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification on failure
        if: failure()
        uses: grafana/shared-workflows/actions/send-slack-message@7b628e7352c2dea057c565cc4fcd5564d5f396c0 # v1.0.0
        with:
          channel-id: C04AF91LPFX #mimir-ci-notifications
          payload: |
            {
              "text": ":sadcomputer: *Automated vendoring of mimir-prometheus into Mimir has failed.*\n<!subteam^S03C2P8659U> please check the <http://spoofed.github.com/grafana/mimir/actions/runs/${{ github.run_id }}|workflow logs> and coordinate fixes for any issues."
            }
