name: test-backport-action

on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    # Only run if the PR is merged and labeled with 'backport xxx'.
    if: ${{ github.event.pull_request.merged == true && contains(format('||{0}', join(github.event.pull_request.labels.*.name, '||')), '||backport ') }}

    steps:
      - name: Checkout grafana-github-actions
        uses: actions/checkout@v4
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          # pin the version to before https://github.com/grafana/grafana-github-actions/pull/113 because
          # we don't want to have the same strict rules for PR labels
          ref: d284afd314ca3625c23595e9f62b52d215ead7ce

      - name: Install grafana-github-actions
        run: npm install --production --prefix ./actions

      - name: Run backport
        id: backport
        #if: ${{ ! github.event.pull_request.head.repo.fork }}
        uses: ./actions/backport
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labelsToAdd: "backport"
          title: "[{{base}}] {{originalTitle}}"
