name: test-shared-workflow

on:
  workflow_dispatch: # for manual testing

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ./.github/shared/actions/test-action.yaml
